# nixOS VM test for the archive.
#
## Boots a virtual machine containing every version's derivation (each
## evaluated with the nixpkgs generation of its era) and runs a check
##   0.1.5        source-only artifact  -> file presence
##   0.2.0-0.4.0  pre-RPC GUI era       -> binary starts on a virtual
##                                          display (Xvfb): output or
##                                          surviving the 5 s cap
##   0.5.0-0.12.1 pre-RPC era           -> binary links and runs:
##                                          output or surviving the
##                                          5 s cap (fresh datadir)
##   0.13.0-31.1  stable RPC era        -> -version + regtest RPC
##                                          round-trip (strict)
##
## The VM build uses the cache for every output whose evaluation is
## unchanged; a derivation whose inputs drifted since its build (e.g.
## a vendored dependency was fixed) is rebuilt once and cached.
## Usage (from the repo root):
#   tests/vm/run-vm-test.sh
##
## The era nixpkgs checkouts are located by the environment variables
## NIXPKGS_16_09, NIXPKGS_20_09, NIXPKGS_23_11, NIXPKGS_25_05 (each an
## absolute path), so this file carries no machine-specific paths.
{ pkgs ? import <nixpkgs> { system = builtins.currentSystem; } }:

let
  lib = pkgs.lib;

  # The archive: every version directory under ../../core (sorted).
  # Only real directories are versions — core/ also holds _deps/
  # (shared build helpers), which is not a release. readDir entries
  # are a string on some nix versions and a { type } set on others.
  isDirEntry = e:
    if builtins.isAttrs e then e.type == "directory" else e == "directory";
  versions = builtins.attrNames (lib.listToAttrs (lib.map (v: { name = v; value = v; }) (
    let
      cd = builtins.readDir ../../core;
    in lib.filter (d: d != "_deps" && isDirEntry cd.${d}) (builtins.attrNames cd)
  )));
  kindOf = version:
    if version == "0.1.5" then "src"
    else if lib.versionOlder version "0.5.0" then "gui"      # 0.2.x-0.4.x: wx GUI, single `bitcoin` binary, no -version flag
    else if lib.versionOlder version "0.13.0" then "rpc-skip"  # 0.5.0-0.12.1: no reliable -version flag; rpcpassword marker, RPC best-effort
    else "rpc-strict";

  # Each version's derivation is imported with the nixpkgs generation
  # that era was built with. The evaluation reproduces the already-built
  # derivation exactly (identical store paths — verified), so the VM
  # build only pulls existing outputs into the closure, never rebuilds.
  # A bare store path cannot be made a derivation input, but a
  # derivation can — and its out is exactly the built output.
  # Era nixpkgs checkouts, located by environment variable so this
  # file carries no machine-specific paths (see run-vm-test.sh).
  eraPath = var:
    let
      p = builtins.getEnv var;
    in if p == ""
      then throw "tests/vm: set ${var} to the absolute path of that era's nixpkgs checkout"
      else p;

  eras = {
    "16.09" = import (eraPath "NIXPKGS_16_09") { system = builtins.currentSystem; };
    "20.09" = import (eraPath "NIXPKGS_20_09") { system = builtins.currentSystem; };
    "23.11" = import (eraPath "NIXPKGS_23_11") { system = builtins.currentSystem; };
    "25.05" = import (eraPath "NIXPKGS_25_05") { system = builtins.currentSystem; };
  };

  eraPkg = version:
    let
      era =
        if lib.versionOlder version "0.13.0" then eras."16.09"   # 0.1.5-0.12.1
        else if lib.versionOlder version "22.0" then eras."20.09"  # 0.13.0-0.21.2
        else if lib.versionOlder version "29.0" then eras."23.11"  # 22.0-28.4
        else eras."25.05";                                       # 29.0-31.1
    in (import ../../core/${version}/default.nix) { pkgs = era; };
  runner = pkgs.writeScript "archive-runner" ''
    #!/bin/sh
    # Generated by tests/vm/default.nix — do not edit.
    set -u
    fail=0

    bin_of() {
      b="$1/bin/bitcoind"
      if [ ! -x "$b" ]; then
        f=$(ls "$1/bin" 2>/dev/null | head -1)
        [ -n "$f" ] && b="$1/bin/$f"
      fi
      echo "$b"
    }

    run_cap() {
      # run_cap SECS BIN ARGS... — captures up to 5 lines of the
      # binary's output and returns the binary's exit status. Output
      # goes to a file, never a pipe: a binary that forks a child
      # surviving `timeout` would hold the pipe's write end open
      # forever and the command substitution would hang the runner
      # (observed on 0.2.1: the gui binary's child survived the TERM
      # and the suite stalled 11+ min with no progress). -k 5
      # escalates TERM to KILL after 5 s, so a binary stuck in a
      # signal handler is reaped too. rc=124 means the binary was
      # still running at the cap (survived).
      t="$1"; b="$2"; shift 2
      f=$(mktemp /tmp/cap.XXXXXX)
      if [ "$t" -gt 0 ]; then
        timeout -k 5 "$t" "$b" "$@" >"$f" 2>&1
      else
        "$b" "$@" >"$f" 2>&1
      fi
      rc=$?
      head -5 "$f"
      rm -f "$f"
      return "$rc"
    }

    do_version() {
      ver="$1"; out="$2"
      mode=""
      if [ "$#" -ge 3 ]; then mode="$3"; fi
      [ -z "$mode" ] && mode=ver
      b=$(bin_of "$out")
      if [ -z "$b" ] || [ ! -x "$b" ]; then
        echo "FAIL $ver: no binary in $out/bin"; fail=1; return 1
      fi
      if [ "$mode" = "early" ]; then
        # v0.5.0-v0.12.1: output across this era is inconsistent —
        # some versions print an rpcpassword diagnostic and exit,
        # others (0.6.0) start silently and run on. The check is
        # therefore "links and runs": any output OR surviving the
        # 5 s cap. A fresh datadir avoids cross-version wallet locks.
        d=$(mktemp -d /tmp/btc-XXXXXX)
        o=$(run_cap 5 "$b" -version -datadir="$d"); rc=$?
        rm -rf "$d"
        if [ -n "$o" ] || [ "$rc" = "124" ]; then
          echo "OK $ver: binary runs (pre-RPC era)"
        else
          echo "FAIL $ver: binary produced no output and did not survive (rc=$rc): $(printf '%s' "$o" | head -1)"
          fail=1; return 1
        fi
        return 0
      fi
      o=$(run_cap 20 "$b" -version); rc=$?
      if ! printf '%s' "$o" | grep -q "$ver"; then
        echo "FAIL $ver: -version output does not contain $ver (rc=$rc): $(printf '%s' "$o" | head -3 | tr '\n' '|')"
        fail=1; return 1
      fi
      echo "OK $ver: $(printf '%s\n' "$o" | head -1)"
    }

    do_src() {
      ver="$1"; out="$2"
      if [ -f "$out/src/main.cpp" ]; then
        echo "OK $ver: source tree present"
      else
        echo "FAIL $ver: src/main.cpp missing"; fail=1; return 1
      fi
    }
    do_gui() {
      ver="$1"; out="$2"
      b=$(bin_of "$out")
      if [ -z "$b" ] || [ ! -x "$b" ]; then
        echo "FAIL $ver: no binary in $out/bin"; fail=1; return 1
      fi
      # v0.2.x-v0.4.x: single wx-GUI+node binary, no -version flag.
      # Headless VM: wx needs an X server, so run under Xvfb. The
      # check is "links and runs": the app keeps running on the
      # virtual display (rc=124 at the 5 s cap); a broken binary
      # (missing library, crash) exits early with no usable output.
      # v0.3.6-v0.3.20.2 additionally daemonize at startup: main()
      # forks under __WXGTK__ when no command-line arg is passed;
      # the parent pthread_exit(0)s (so rc=0 and no output — the
      # child's stdout is block-buffered into the file) and the
      # child keeps running the node. rc=0 is therefore OK for
      # those iff the child carrying our -datadir is still alive;
      # it is killed so port 8333 stays free for the next version.
      d=$(mktemp -d /tmp/btc-XXXXXX)
      Xvfb :99 >/dev/null 2>&1 &
      xpid=$!
      sleep 1
      o=$(DISPLAY=:99 run_cap 5 "$b" -datadir="$d"); rc=$?
      kill "$xpid" >/dev/null 2>&1
      if [ -n "$o" ] || [ "$rc" = "124" ]; then
        echo "OK $ver: gui binary runs (headless X)"
        rm -rf "$d"
        return 0
      fi
      # Daemonizing fork: the parent exited early; the child keeps
      # our -datadir in its command line.
      if pgrep -f "datadir=$d" >/dev/null 2>&1; then
        pkill -f "datadir=$d" 2>/dev/null; sleep 2
        pkill -9 -f "datadir=$d" 2>/dev/null
        echo "OK $ver: gui binary daemonized (child node running)"
        rm -rf "$d"
        return 0
      fi
      echo "FAIL $ver: gui binary produced no output and did not survive (rc=$rc): $(printf '%s' "$o" | head -1)"
      rm -rf "$d"
      fail=1; return 1
    }

    do_rpc() {
      strict="$1"; ver="$2"; out="$3"
      case "$ver" in
        # v0.5.0-v0.12.1: no -regtest yet (added 0.6.0rc1) and
        # -version output is inconsistent across the era (some
        # versions print an rpcpassword diagnostic and exit); the
        # startup check is the whole check for these versions.
        # 0.13.0+ has a clean -version and the strict check applies.
        0.5.*|0.6.*|0.7.*|0.8.*|0.9.*|0.10.*|0.11.*|0.12.*)
          do_version "$ver" "$out" early || return 1 ;;
        *) do_version "$ver" "$out" || return 1 ;;
      esac
      b=$(bin_of "$out")
      d=$(mktemp -d /tmp/btc-XXXXXX)
      # -rpcpassword (not the 0.15.0+ -rpcpass alias): pre-0.15
      # bitcoind silently ignores unknown flags, so -rpcpass would
      # leave -rpcpassword unset and fall back to cookie auth,
      # failing every Basic-auth RPC roundtrip below.
      # stdout to a file, not the runner's output: the -daemon parent
      # prints "Bitcoin Core starting" to stdout before forking, and
      # that line would land in runner.out as a non-verdict line.
      timeout -k 5 30 "$b" -regtest -daemon -datadir="$d" -server \
        -rpcuser=archive -rpcpassword=archivepass -rpcport=18443 \
        -rpcbind=127.0.0.1 >"$d.out" 2>"$d.err"
      if [ "$?" -ne 0 ]; then
        dbg=$(tail -3 "$d.err" 2>/dev/null | tr '\n' '|')
        if [ "$strict" = "1" ]; then
          echo "FAIL $ver: regtest daemon did not start: $dbg"; fail=1
        else
          echo "SKIP-RPC $ver: daemon did not start (flag era): $dbg"
        fi
        rm -rf "$d" "$d.out" "$d.err" 2>/dev/null
        return 1
      fi
      rpc=""
      i=0
      while [ $i -lt 45 ]; do
        sleep 1
        rpc=$(curl -s -m 5 -u archive:archivepass http://127.0.0.1:18443/ \
              -d '{"method":"getblockcount"}' 2>/dev/null) || rpc=""
        # only a genuine result:0 ends the loop: a -28 "Loading
        # wallet" warmup error must keep polling, not break (it
        # orphans a daemon that -stop cannot kill during warmup)
        case "$rpc" in *'"result":0'*) break ;; esac
        i=$((i+1))
      done
      case "$rpc" in
        *'"result":0'*)
          # a healthy daemon answers -stop in seconds; cap it and
          # fall back to a datadir kill so one wedged daemon can
          # never stall the suite (a hung RPC reply would otherwise
          # block bitcoind -stop forever)
          timeout -k 5 15 "$b" -stop -datadir="$d" \
            -rpcuser=archive -rpcpassword=archivepass >/dev/null 2>&1 \
            || pkill -f "datadir=$d" 2>/dev/null
          i=0
          while [ $i -lt 30 ]; do
            sleep 1
            pgrep -f "bitcoind .*datadir=$d" >/dev/null 2>&1 || break
            i=$((i+1))
          done
          rm -rf "$d" "$d.out" "$d.err" 2>/dev/null
          echo "OK $ver: regtest rpc getblockcount=0"
          ;;
        *)
          if [ "$strict" = "1" ]; then
            echo "FAIL $ver: rpc getblockcount: $rpc"
            fail=1
          else
            echo "SKIP-RPC $ver: rpc getblockcount: $rpc"
          fi
          # RPC -stop is a no-op while the daemon is still in warmup
          # (-28 rejects every command), so kill it by datadir
          pkill -f "datadir=$d" 2>/dev/null
          sleep 2   # let the RPC port be released for the next version
          rm -rf "$d" "$d.out" "$d.err" 2>/dev/null
          return 1
          ;;
      esac
    }

    ${lib.concatMapStringsSep "\n" (version:
      let k = kindOf version;
          out = eraPkg version;
      in
      if k == "src" then
        "do_src ${version} ${out.outPath}"
      else if k == "gui" then
        "do_gui ${version} ${out.outPath}"
      else if k == "ver" then
        "do_version ${version} ${out.outPath}"
      else if k == "rpc-skip" then
        "do_rpc 0 ${version} ${out.outPath}"
      else
        "do_rpc 1 ${version} ${out.outPath}"
    ) versions}

    echo "=== runner done ==="
    exit $fail
  '';
in
# make-test-python.nix is curried: (import ...) f { system, pkgs }
# returns { test; nodes; driver; } — `test` is the VM test derivation.
# writeScript yields a bare file, but environment.systemPackages needs
# a directory, so wrap the runner in a package layout.
let
  runnerPkg = pkgs.runCommand "archive-runner" {} ''
    mkdir -p $out/bin
    cp ${runner.outPath} $out/bin/archive-runner
    chmod +x $out/bin/archive-runner
  '';

  testSet = (import (pkgs.path + "/nixos/tests/make-test-python.nix")) ({
    name = "nix-bitcoin-core-archive";
    skipLint = true;

    nodes.machine = {
      # The version derivations themselves are the system packages.
      # Each is evaluated with the nixpkgs generation of its era, so
      # already-built outputs are cache hits; drifted ones (vendored
      # deps changed since their build) are rebuilt once and cached.
      # Dispatch references each derivation's outPath, which is exactly
      # the path present in the VM store.
      environment.systemPackages =
        (builtins.map eraPkg versions)
        ++ [
          runnerPkg
          pkgs.curl
          pkgs.psmisc
          # GUI era (0.2.x-0.4.x) needs an X server in the headless
          # guest.
          pkgs.xorg.xvfb
        ];
    };

    # The test driver is Python: run the full check suite, then fail
    # the test if any result line is FAIL — the failing command's
    # output (the FAIL lines) lands in the nix build log.
    # The runner needs well over 90 minutes in the worst case (137
    # versions, regtest daemon start/stop per version; the 2026-09-22
    # full run ran 88+ minutes and did not finish), so it is launched
    # in the background with its output redirected to a file — NOT
    # teed: the driver's execute() blocks until every writer of its
    # output pipe has exited, and a backgrounded tee holds the pipe's
    # write end open for the whole suite (verified: with tee, the
    # launch command "finished" exactly when the runner did). Progress
    # is made visible by polling the tail of the output file every 90 s
    # and logging it; tee to /dev/console is invisible, because the
    # guest's /dev/console is tty0 (the last console= on the kernel
    # command line), not serial0, and with -nographic the display goes
    # nowhere (verified: marker lines never reached the build log).
    globalTimeout = 21600;

    testScript = ''
      start_all()
      # Redirect before exec so the backgrounded process holds no write
      # end of the driver's output pipe (see the comment above).
      machine.succeed("nohup ${runnerPkg.outPath}/bin/archive-runner > /tmp/runner.out 2>&1 &")
      # Poll every 90 s in the guest: sleep, echo the output so far, then
      # exit non-zero while the runner is alive. The [r] keeps pgrep from
      # matching the wrapper shell whose cmdline holds the literal
      # pattern.
      while True:
          status, tail = machine.execute(
              "sleep 90; "
              "tail -n 25 /tmp/runner.out; "
              "pgrep -f 'archive-[r]unner' >/dev/null && exit 1 || exit 0",
              timeout=300,
          )
          machine.log("PROGRESS: " + tail.rstrip())
          if status == 0:
              break
      # grep -c exits 1 on zero matches, which set -e would kill;
      # `|| true` keeps the count and the exit status. runner.out also
      # carries non-verdict lines: the runner's final "=== runner
      # done ===" marker (and the regtest daemons' stdout used to land
      # here too — the -daemon launch now redirects it to $d.out), so
      # gate on FAIL verdicts specifically, not on "anything not OK".
      # The gate requires all three:
      #   (1) no ^FAIL verdict lines — every do_* failure path both
      #       prints "FAIL $ver: ..." and sets fail=1, so this is
      #       exact;
      #   (2) ^OK line count >= 137 — a runner that died early without
      #       emitting FAIL still has to be caught by the count;
      #   (3) the last line of runner.out is the runner's own
      #       "=== runner done ===" marker. The do_* functions never
      #       exit the runner (they only set fail), so the marker is
      #       reached iff every generated version invocation ran.
      #       (2) alone is not sufficient: a runner killed mid-suite
      #       after enough two-line versions (0.13.0+ prints a
      #       -version line AND an rpc line) can cross 137 OK lines
      #       with versions still unchecked.
      # Log the FAIL lines (with diagnostics) when the run has
      # failures; a green run emits nothing. The driver only records
      # the output of failed commands, so this is what makes the full
      # per-version verdict list visible in the build log.
      machine.succeed(
          "out=$(grep -E '^FAIL' /tmp/runner.out || true); "
          "if [ -n \"$out\" ]; then printf '%s\\n' \"$out\"; exit 1; fi"
      )
      machine.succeed(
          "ok=$(grep -c '^OK' /tmp/runner.out || true); "
          "sk=$(grep -c '^SKIP-RPC' /tmp/runner.out || true); "
          "fl=$(grep -c '^FAIL' /tmp/runner.out || true); "
          "echo SUMMARY: ok=$ok skip-rpc=$sk fail=$fl total=$((ok+sk+fl)); "
          "grep -v '^OK' /tmp/runner.out | tail -30; "
          "last=$(tail -n 1 /tmp/runner.out); "
          "if [ \"$fl\" -gt 0 ] || [ \"$ok\" -lt ${toString (builtins.length versions)} ] || [ \"$last\" != \"=== runner done ===\" ]; then exit 1; fi"
      )
      machine.shutdown()
    '';
  });
in
testSet {
  system = pkgs.system;
  pkgs = pkgs;
}
