# nixOS VM test for the archive.
#
## Boots a virtual machine containing every version's derivation (each
## evaluated with the nixpkgs generation of its era) and runs a check
## script that proves each release works:
##
##   0.1.5        source-only artifact  -> file presence
##   0.2.0-0.8.6  pre-RPC era           -> `bitcoind -version`
##   0.9.0-0.12.1 early RPC era         -> -version, regtest RPC best-effort
##   0.13.0-31.1  stable RPC era        -> -version + regtest RPC
##                                          round-trip (strict)
##
## The VM build uses the cache for every output whose evaluation is
## unchanged; a derivation whose inputs drifted since its build (e.g.
## a vendored dependency was fixed) is rebuilt once and cached.
## Usage (from the repo root):
#   tests/vm/run-vm-test.sh
##
## The era nixpkgs checkouts are located by the environment variables
## NIXPKGS_16_09, NIXPKGS_20_09, NIXPKGS_23_11, NIXPKGS_25_05 (each an
## absolute path), so this file carries no machine-specific paths.
{ pkgs ? import <nixpkgs> { system = builtins.currentSystem; } }:

let
  lib = pkgs.lib;

  # The archive: every version directory under ../../core (sorted).
  versions = builtins.attrNames (lib.listToAttrs (lib.map (v: { name = v; value = v; }) (
    lib.filter (d: d != "_deps") (builtins.attrNames (builtins.readDir ../../core))
  )));

  kindOf = version:
    if version == "0.1.5" then "src"
    else if lib.versionOlder version "0.5.0" then "gui"      # 0.2.x-0.4.x: wx GUI, single `bitcoin` binary, no -version flag
    else if lib.versionOlder version "0.13.0" then "rpc-skip"  # 0.5.0-0.12.1: no reliable -version flag; rpcpassword marker, RPC best-effort
    else "rpc-strict";

  # Each version's derivation is imported with the nixpkgs generation
  # that era was built with. The evaluation reproduces the already-built
  # derivation exactly (identical store paths — verified), so the VM
  # build only pulls existing outputs into the closure, never rebuilds.
  # A bare store path cannot be made a derivation input, but a
  # derivation can — and its out is exactly the built output.
  # Era nixpkgs checkouts, located by environment variable so this
  # file carries no machine-specific paths (see run-vm-test.sh).
  eraPath = var:
    let
      p = builtins.getEnv var;
    in if p == ""
      then throw "tests/vm: set ${var} to the absolute path of that era's nixpkgs checkout"
      else p;

  eras = {
    "16.09" = import (eraPath "NIXPKGS_16_09") { system = builtins.currentSystem; };
    "20.09" = import (eraPath "NIXPKGS_20_09") { system = builtins.currentSystem; };
    "23.11" = import (eraPath "NIXPKGS_23_11") { system = builtins.currentSystem; };
    "25.05" = import (eraPath "NIXPKGS_25_05") { system = builtins.currentSystem; };
  };

  eraPkg = version:
    let
      era =
        if lib.versionOlder version "0.13.0" then eras."16.09"   # 0.1.5-0.12.1
        else if lib.versionOlder version "22.0" then eras."20.09"  # 0.13.0-0.21.2
        else if lib.versionOlder version "29.0" then eras."23.11"  # 22.0-28.4
        else eras."25.05";                                       # 29.0-31.1
    in (import ../../core/${version}/default.nix) { pkgs = era; };
  runner = pkgs.writeScript "archive-runner" ''
    #!/bin/sh
    # Generated by tests/vm/default.nix — do not edit.
    set -u
    fail=0

    bin_of() {
      b="$1/bin/bitcoind"
      if [ ! -x "$b" ]; then
        f=$(ls "$1/bin" 2>/dev/null | head -1)
        [ -n "$f" ] && b="$1/bin/$f"
      fi
      echo "$b"
    }

    do_version() {
      ver="$1"; out="$2"; mode="$${3:-ver}"
      b=$(bin_of "$out")
      if [ -z "$b" ] || [ ! -x "$b" ]; then
        echo "FAIL $ver: no binary in $out/bin"; fail=1; return
      fi
      if [ "$mode" = "early" ]; then
        # v0.5.0-v0.12.1 predate the -version flag: any arg makes the
        # binary attempt a node start, which prints the
        # rpcpassword diagnostic. That marker proves it links and runs.
        # timeout: the binary then keeps running in the foreground
        # (unknown -version arg); head closes the pipe after the marker.
        o=$(timeout 20 "$b" -version 2>&1 | head -5)
        if printf '%s' "$o" | grep -q 'rpcpassword'; then
          echo "OK $ver: binary runs (pre- -version-flag era)"
        else
          echo "FAIL $ver: no startup diagnostic from binary"; fail=1; return
        fi
        return
      fi
      if ! "$b" -version | grep -q "$ver"; then
        echo "FAIL $ver: -version output does not contain $ver"; fail=1; return
      fi
      echo "OK $ver: $($b -version | head -1)"
    }

    do_src() {
      ver="$1"; out="$2"
      if [ -f "$out/src/main.cpp" ]; then
        echo "OK $ver: source tree present"
      else
        echo "FAIL $ver: src/main.cpp missing"; fail=1
      fi
    }
    do_gui() {
      ver="$1"; out="$2"
      b=$(bin_of "$out")
      if [ -z "$b" ] || [ ! -x "$b" ]; then
        echo "FAIL $ver: no binary in $out/bin"; fail=1; return
      fi
      # v0.2.x-v0.4.x: single wx-GUI+node binary, no -version flag.
      # Headless VM: wx init fails on the missing X display; any output
      # from the short run proves the binary links and starts.
      o=$(timeout 20 "$b" -printtoconsole 2>&1 | head -3)
      if [ -n "$o" ]; then
        echo "OK $ver: binary runs (gui era, no -version flag)"
      else
        echo "FAIL $ver: gui binary produced no output"; fail=1
      fi
    }

    do_rpc() {
      strict="$1"; ver="$2"; out="$3"
      case "$ver" in
        # pre-0.13: no -regtest flag; the startup-marker check is the
        # whole check for these versions.
        0.*) do_version "$ver" "$out" early; return ;;
        *) do_version "$ver" "$out" || return ;;
      esac
      b=$(bin_of "$out")
      d=$(mktemp -d /tmp/btc-XXXXXX)
      # timeout: pre-0.13 binaries do not know -regtest; a warning-only
      # parse can leave them running in the foreground forever.
      timeout 30 "$b" -regtest -daemon -datadir="$d" -server \
        -rpcuser=archive -rpcpass=archive -rpcport=18443 \
        -rpcbind=127.0.0.1 >/dev/null 2>&1
      if [ "$?" -ne 0 ]; then
        if [ "$strict" = "1" ]; then
          echo "FAIL $ver: regtest daemon did not start"; fail=1
        else
          echo "SKIP-RPC $ver: daemon did not start (flag era)"
        fi
        rm -rf "$d"; return
      fi
      rpc=""
      i=0
      while [ $i -lt 45 ]; do
        sleep 1
        rpc=$(curl -s -u archive:archive http://127.0.0.1:18443/ \
              -d '{"method":"getblockcount"}' 2>/dev/null) || rpc=""
        [ -n "$rpc" ] && break
        i=$((i+1))
      done
      case "$rpc" in
        *'"result":0'*)
          "$b" -stop -datadir="$d" \
            -rpcuser=archive -rpcpass=archive >/dev/null 2>&1
          i=0
          while [ $i -lt 30 ]; do
            sleep 1
            pgrep -f "bitcoind .*datadir=$d" >/dev/null 2>&1 || break
            i=$((i+1))
          done
          rm -rf "$d"
          echo "OK $ver: regtest rpc getblockcount=0"
          ;;
        *)
          if [ "$strict" = "1" ]; then
            echo "FAIL $ver: rpc getblockcount: $rpc"
            fail=1
          else
            echo "SKIP-RPC $ver: rpc getblockcount: $rpc"
          fi
          "$b" -stop -datadir="$d" \
            -rpcuser=archive -rpcpass=archive >/dev/null 2>&1
          rm -rf "$d"
          ;;
      esac
    }

    ${lib.concatMapStringsSep "\n" (version:
      let k = kindOf version;
          out = eraPkg version;
      in
      if k == "src" then
        "do_src ${version} ${out.outPath}"
      else if k == "gui" then
        "do_gui ${version} ${out.outPath}"
      else if k == "ver" then
        "do_version ${version} ${out.outPath}"
      else if k == "rpc-skip" then
        "do_rpc 0 ${version} ${out.outPath}"
      else
        "do_rpc 1 ${version} ${out.outPath}"
    ) versions}

    echo "=== runner done ==="
    exit $fail
  '';
in
# make-test-python.nix is curried: (import ...) f { system, pkgs }
# returns { test; nodes; driver; } — `test` is the VM test derivation.
# writeScript yields a bare file, but environment.systemPackages needs
# a directory, so wrap the runner in a package layout.
let
  runnerPkg = pkgs.runCommand "archive-runner" {} ''
    mkdir -p $out/bin
    cp ${runner.outPath} $out/bin/archive-runner
    chmod +x $out/bin/archive-runner
  '';

  testSet = (import (pkgs.path + "/nixos/tests/make-test-python.nix")) ({
    name = "nix-bitcoin-core-archive";
    skipLint = true;

    nodes.machine = {
      # The version derivations themselves are the system packages.
      # Each is evaluated with the nixpkgs generation of its era, so
      # already-built outputs are cache hits; drifted ones (vendored
      # deps changed since their build) are rebuilt once and cached.
      # Dispatch references each derivation's outPath, which is exactly
      # the path present in the VM store.
      environment.systemPackages =
        (builtins.map eraPkg versions)
        ++ [
          runnerPkg
          pkgs.curl
          pkgs.psmisc
        ];
    };

    # The test driver is Python: run the full check suite, then fail
    # the test if any result line is FAIL — the failing command's
    # output (the FAIL lines) lands in the nix build log.
    # The runner needs well over 900 s (137 versions, regtest daemon
    # start/stop per version), so it is launched in the background and
    # the driver polls for its exit (wait_until_succeeds takes an
    # explicit timeout; makeTest has no timeout parameter in 25.05).
    globalTimeout = 5400;

    testScript = ''
      start_all()
      machine.succeed("nohup ${runnerPkg.outPath}/bin/archive-runner 2>&1 | tee /tmp/runner.out &")
      machine.wait_until_succeeds("! pgrep -f 'archive-[r]unner' >/dev/null", timeout=5000)
      machine.succeed(
          "ok=$(grep -c '^OK' /tmp/runner.out); "
          "sk=$(grep -c '^SKIP-RPC' /tmp/runner.out); "
          "fl=$(grep -c '^FAIL' /tmp/runner.out); "
          "echo SUMMARY: ok=$ok skip-rpc=$sk fail=$fl total=$((ok+sk+fl)); "
          "grep -v '^OK' /tmp/runner.out | tail -30; "
          "if [ \"$fl\" -gt 0 ]; then exit 1; fi"
      )
      machine.shutdown()
    '';
  });
in
testSet {
  system = pkgs.system;
  pkgs = pkgs;
}
